
cerad_tourn__game_schedule__show:
    path:  /game-schedule
    defaults: 
        _controller: cerad_tourn__game_schedule__show_controller:action
        _model:      cerad_tourn__game_schedule__show_model_factory
        _project:    ~
        _template: '@CeradTourn\GameSchedule\Show\GameScheduleShowPage.html.twig'
        
cerad_tourn__referee_schedule__show:
    path:  /referee-schedule
    defaults: 
        _controller: cerad_tourn__referee_schedule__show_controller:action
        _model:      cerad_tourn__referee_schedule__show_model_factory
        _form:       cerad_tourn__referee_schedule__show_form_factory
        _project:    ~
        _template: '@CeradTourn\RefereeSchedule\Show\RefereeScheduleShowPage.html.twig'

cerad_tourn__game_official__self_assign:
  path:  /game-official/game/{game}/slot/{slot}/self-assign
  defaults: 
    _controller: cerad_tourn__game_official__self_assign_controller:action
    _model:      cerad_tourn__game_official__self_assign_model_factory
    _form:       cerad_tourn__game_official__self_assign_form_factory
    _template: '@CeradTourn\GameOfficial\SelfAssign\GameOfficialSelfAssignPage.html.twig'
    _project:    ~
    _userPerson: ~
    
# Game Official (singular) implies only one slot
cerad_game__project__game_official__assign_by_user:
    path:  /project/{_project}/game/{_game}/official/{_game_official}/assign-by-user
    defaults:
        _controller: cerad_game__project__game_official__assign_by_user__controller:assignAction
        _model:      cerad_game__project__game_official__assign_by_user__model_factory
        _form:       cerad_game__project__game_official__assign_by_user__form_factory
        _view:       cerad_game__project__game_official__assign_by_user__view_factory
        _template: '@CeradGame/Project/GameOfficial/AssignByUser/AssignByUserIndex.html.twig'
        _redirect:   cerad_tourn_schedule_official_list
        _role:       ROLE_USER
        _user_person: required

# ===================================================
# Override the create user person  to allows adding referee certification
# Want to  break this into steps later on
#
# Creating a user when you already know the project is a bit different
# From creating a user to be used for multiple projects
cerad_tourn__user_person__create:
  path: /user-person/create
  defaults:
    _model:      cerad_tourn__user_person__create_model_factory
    _form:       cerad_tourn__user_person__create_form_factory
    _controller: cerad_tourn__user_person__create_controller:action
    _template: '@CeradTourn\UserPerson\Create\UserPersonCreatePage.html.twig'
    _project:  ~
    
cerad_tourn__user_person__create_form:
  path: /user-person/create-form
  defaults:
    _route:      cerad_tourn__user_person__create
    _model:      cerad_tourn__user_person__create_model_factory
    _form:       cerad_tourn__user_person__create_form_factory
    _controller: cerad_tourn__user_person__create_controller:action
    _template: '@CeradTourn\UserPerson\Create\UserPersonCreateForm.html.twig'
    _project:  ~

# =======================================================
cerad_tourn__welcome:
  path:  /welcome
  defaults: 
    _controller: cerad_tourn__welcome__controller:action
    _model:      cerad_tourn__welcome__model_factory
    _template: '@CeradTourn\Welcome\WelcomePage.html.twig'
    _project:    ~
    
cerad_tourn__home:
  path:  /home
  defaults: 
    _controller: cerad_tourn__home__controller:action
    _model:      cerad_tourn__home__model_factory
    _template: '@CeradTourn\Home\HomePage.html.twig'
    _project:    ~
    _userPerson: ~
        
cerad_tourn__index:
  path:  /
  defaults: 
    _controller: cerad_tourn__index__controller:action

