services:
  
# =======================================================================
# Action: GameOfficialSelfAssign
#
  cerad_tourn__game_official__self_assign_model_factory:
    class: Cerad\Bundle\TournBundle\Action\GameOfficial\AssignByUser\GameOfficialSelfAssignModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_person__person_repository'

  cerad_tourn__game_official__self_assign_form_factory:
    class: Cerad\Bundle\TournBundle\Action\GameOfficial\SelfAssign\GameOfficialSelfAssignFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_tourn__game_official__self_assign_controller:
    class: Cerad\Bundle\TournBundle\Action\GameOfficial\SelfAssign\GameOfficialSelfAssignController
    calls:
      - [setRouter,         ['@router']]
      - [setTemplating,     ['@templating']]
      - [setSecurityContext,['@security.context']]
      
# =======================================================================
# Action: RefereeScheduleShow
#
  cerad_tourn__referee_schedule__show_model_factory:
    class: Cerad\Bundle\TournBundle\Action\RefereeSchedule\Show\RefereeScheduleShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'

  cerad_tourn__referee_schedule__show_form_factory:
    class: Cerad\Bundle\TournBundle\Action\RefereeSchedule\Show\RefereeScheduleShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_tourn__referee_schedule__show_controller:
    class: Cerad\Bundle\TournBundle\Action\RefereeSchedule\Show\RefereeScheduleShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
# =======================================================================
# Action: GameScheduleShow
#
  cerad_tourn__game_schedule__show_model_factory:
    class: Cerad\Bundle\TournBundle\Action\GameSchedule\Show\GameScheduleShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_person__person_repository'

  cerad_tourn__game_schedule__show_form_factory:
    class: Cerad\Bundle\TournBundle\Action\GameSchedule\Show\GameScheduleShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_tourn__game_schedule__show_controller:
    class: Cerad\Bundle\TournBundle\Action\GameSchedule\Show\GameScheduleShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]

# =======================================================================
# Action: CreateUserPerson
# TODO: Paramertize the class names
#
  cerad_tourn__user_person__create_model_factory:
    class: Cerad\Bundle\TournBundle\Action\UserPerson\Create\UserPersonCreateModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_user__user_manager'
      - '@cerad_person__person_repository'
      - '%cerad_fed_role_default%'

  cerad_tourn__user_person__create__form_factory:
    class: Cerad\Bundle\TournBundle\Action\UserPerson\Create\UserPersonCreateFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_tourn__user_person__create__controller:
    class: Cerad\Bundle\TournBundle\Action\UserPerson\Create\UserPersonCreateController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
             
  
# ==========================================================
# Action: Home
  cerad_tourn__home__controller:
    class: Cerad\Bundle\TournBundle\Action\Home\HomeController
    calls:
      - [setRouter,         ['@router']]
      - [setTemplating,     ['@templating']]
      - [setSecurityContext,['@security.context']]
             
  cerad_tourn__home__model_factory:
    class: Cerad\Bundle\TournBundle\Action\Home\HomeModel
    arguments:
      - '@cerad_person__person_repository'
    
# ==========================================================
# Action: Welcome
  cerad_tourn__welcome__controller:
    class: Cerad\Bundle\TournBundle\Action\Welcome\WelcomeController
    calls:
      - [setRouter,         ['@router']]
      - [setTemplating,     ['@templating']]
      - [setSecurityContext,['@security.context']]
             
  cerad_tourn__welcome__model_factory:
    class: Cerad\Bundle\TournBundle\Action\Welcome\WelcomeModel

# ==========================================================
# Action: Index
  cerad_tourn__index__controller:
    class: Cerad\Bundle\TournBundle\Action\Welcome\IndexController
    calls:
      - [setRouter,         ['@router']]
    # - [setTemplating,     ['@templating']]
      - [setSecurityContext,['@security.context']]


